### ISSUE TITLE
Running cppcheck gives an error in the Docker container

### ISSUE THREAD

**Issue by RomainTT** [Harvester57/docker-cppcheck#1]
I got the following error message:

```
cppcheck: Failed to load library configuration file 'std.cfg'. File not found
```

I think it comes from [this COPY line](https://github.com/Harvester57/docker-cppcheck/blob/9e77276b14f7208c2f2512a6cbcc9a12c4c995ce/Dockerfile#L27) which is insufficient for a full installation. `cppcheck` needs some configuration files. I don’t know how to do it in the container, but `make install` copies all the necessary files.

**Comment by Harvester57** [comment]
Thanks for the report, I changed the build logic in https://github.com/Harvester57/docker-cppcheck/commit/c4c1bdf42eb0abc0e0309c7812b0740518d8476c, can you try to pull the `latest` tag, and check if you still have the problem ?

The final image is bigger than before, but I will try to reduce it's size

**Comment by RomainTT** [comment]
> 

It works ! Thank you 😄

**Comment by Harvester57** [comment]
Yay ! I'm closing this one for now, and I opened another issue regarding the final image size, will get back on it soon :)
